---
k3s_version: v1.18.6+k3s1
ansible_user: mattias
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--flannel-backend=ipsec --disable servicelb"
extra_agent_args: ""
